[grpc]
host = "0.0.0.0"
port = 50052

[piper]
binary = "/home/jetson/tts/piper/piper/piper"
model = "/home/jetson/tts/piper/voices/en_US-lessac-medium.onnx"
extra_args = []

[playback]
command = "aplay"
speaker_device = "default"

[vtt]
enabled = true
#backend = "faster-whisper"
#model = "base"
#language = "en"
#compute_type = "float32"
#beam_size = 5
#vad_filter = false
# For Jetson-local NVIDIA Riva ASR:
backend = "riva"
riva_uri = "localhost:50051"
riva_language_code = "en-US"
riva_model = "conformer-en-US-asr-streaming-asr-bls-ensemble"
riva_automatic_punctuation = false
riva_use_ssl = false

[wake_word]
enabled = true
backend = "openwakeword"
model = "models/Robot_20260330_000935.onnx"
threshold = 0.2

[microphone]
device = "ReSpeaker Lite: USB Audio (hw:0,0)"

[sounds]
wake_triggered = "sounds/switch_005.wav"
recording_sent = "sounds/switch_007.wav"
