[grpc]
host = "0.0.0.0"
port = 50052

[piper]
binary = "/home/jetson/tts/piper/piper/piper"
model = "/home/jetson/tts/piper/voices/en_US-danny-low.onnx"
extra_args = []

[playback]
command = "aplay"
speaker_device = "default"

[vtt]
enabled = false
selected_backend = "conformer"
trigger = "wake_word"
command_prefixes = ["robot"]
voice_activity_rms_threshold = 250.0
voice_activity_cooldown_seconds = 1.2
voice_activity_preroll_seconds = 1.2

[vtt.backends.whisper_base]
type = "faster-whisper"
model = "small"
language = "en"
compute_type = "float32"
beam_size = 5
vad_filter = false

[vtt.backends.conformer]
type = "riva"
uri = "localhost:50051"
language_code = "en-US"
model = "conformer-en-US-asr-streaming-asr-bls-ensemble"
automatic_punctuation = true
use_ssl = false

[vtt.backends.riva_0_6b]
type = "riva"
uri = "localhost:50051"
language_code = "en-US"
model = "parakeet-0.6b-en-us-asr-streaming"
automatic_punctuation = true
use_ssl = false

[wake_word]
backend = "openwakeword"
model = "models/Hey_Robot_20260401_210600.onnx"
threshold = 0.35

[microphone]
device = "ReSpeaker Lite: USB Audio (hw:0,0)"

[sounds]
wake_triggered = "sounds/switch_005.wav"
recording_sent = "sounds/switch_007.wav"
