[grpc]
host = "0.0.0.0"
port = 50052

[piper]
binary = "/home/jetson/tts/piper/piper/piper"
model = "/home/jetson/tts/piper/voices/en_US-lessac-medium.onnx"
extra_args = []

[playback]
command = "aplay"
speaker_device = "default"

[vtt]
enabled = true
backend = "faster-whisper"
model = "small"
language = "en"

[wake_word]
enabled = true
backend = "openwakeword"
model = "models/Robot_20260330_000935.onnx"
threshold = 0.5

[microphone]
device = "ReSpeaker Lite: USB Audio (hw:0,0)"

[sounds]
wake_triggered = "sounds/switch_005.ogg"
recording_sent = "sounds/switch_007.ogg"
